/** Refresh the verbatim, licensed source used only for transcript matching.
 * Usage: npx tsx scripts/sync-quran-speech.ts [--from path-to-original-download]
 * Review the source's update notice and run the speech-guard tests before release.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const url =
  "https://tanzil.net/pub/download/index.php?quranType=simple-clean&outType=txt-2&agree=true";
const from = process.argv.indexOf("--from");
let bytes: Buffer;
if (from >= 0) {
  if (!process.argv[from + 1])
    throw new Error("Missing original download path.");
  bytes = readFileSync(process.argv[from + 1]);
} else {
  const response = await fetch(url, { signal: AbortSignal.timeout(20_000) });
  if (!response.ok)
    throw new Error(`Tanzil download failed: ${response.status}`);
  bytes = Buffer.from(await response.arrayBuffer());
}
const original = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
if (!Buffer.from(original, "utf8").equals(bytes))
  throw new Error("UTF-8 round trip differs.");
const records = original
  .split(/\r?\n/)
  .filter((line) => /^\d+\|\d+\|/.test(line));
const keys = records.map((line) => line.split("|").slice(0, 2).join(":"));
if (
  records.length !== 6236 ||
  new Set(keys).size !== 6236 ||
  keys[0] !== "1:1" ||
  keys.at(-1) !== "114:6"
) {
  throw new Error(
    "Unexpected Quran source structure; review before replacing.",
  );
}
const notice = original.slice(
  original.indexOf(
    "#====================================================================",
  ),
);
if (
  !notice.includes("Tanzil Quran Text (Simple Clean, Version 1.1)") ||
  !notice.includes("CHANGING IT IS NOT ALLOWED") ||
  !notice.includes("Creative Commons Attribution 3.0")
) {
  throw new Error(
    "Source notice/version changed; review the new source and terms.",
  );
}
const metadata = {
  provider: "Tanzil Project",
  version: "1.1",
  textType: "Simple Clean",
  url,
  licenseUrl: "https://tanzil.net/docs/text_license",
  attributionUrl: "https://tanzil.net",
  updatesUrl: "https://tanzil.net/updates/",
  retrieved: new Date().toISOString().slice(0, 10),
  verseCount: 6236,
  sha256: createHash("sha256").update(bytes).digest("hex"),
};
const module = `// Generated by scripts/sync-quran-speech.ts; do not edit the source text.\n// Original numbered download and license are preserved verbatim in the string.\n/*!\n${notice.trimEnd()}\n*/\nexport const QURAN_SPEECH_SOURCE = ${JSON.stringify(metadata)} as const;\nexport const QURAN_SPEECH_CORPUS = ${JSON.stringify(original)};\n`;
writeFileSync("apps/sakina/lib/quran-speech-data.ts", module, "utf8");
console.log(
  JSON.stringify({
    provider: metadata.provider,
    verseCount: records.length,
    sourceBytes: bytes.length,
    sha256: metadata.sha256,
  }),
);
